name: bibliotheksverwaltung

services:
  postgres:
    build: .
    environment:
      POSTGRES_DB: Bibliotheksverwaltung
      POSTGRES_INITDB_ARGS: '--locale=de_DE.UTF-8 --lc-collate=de_DE.UTF-8 --lc-ctype=de_DE.UTF-8 --lc-messages=en_US.UTF-8 --lc-monetary=de_DE.UTF-8 --lc-numeric=de_DE.UTF-8 --lc-time=de_DE.UTF-8'
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER_FILE: /run/secrets/postgres-admin-username
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres-admin-password
    ports:
      - 5432:5432
    secrets:
      - postgres-admin-username
      - postgres-admin-password
    restart: unless-stopped
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ../datalayer/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ../datalayer/insert.sql:/docker-entrypoint-initdb.d/insert.sql
    healthcheck:
      test:
        [
          'CMD-SHELL',
          'PGPASSWORD=$(cat /run/secrets/postgres-admin-password) pg_isready -U $(cat /run/secrets/postgres-admin-username) -d Bibliotheksverwaltung -h localhost',
        ]
      interval: 30s
      timeout: 10s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:8.10
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - 5050:80
    restart: unless-stopped
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres

secrets:
  postgres-admin-username:
    file: ./secrets/postgres_user.txt
  postgres-admin-password:
    file: ./secrets/postgres_password.txt

volumes:
  pg_data:
  pgadmin_data:
